import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { execSync } from "node:child_process";

export const MERMAID_CLI_VERSION = process.env.MERMAID_CLI_VERSION ?? "11.4.0";

export function listArchitectureMarkdown(archDir) {
  if (!fs.existsSync(archDir)) return [];
  return fs
    .readdirSync(archDir)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .map((f) => path.join(archDir, f));
}

export function extractMermaidBlocks(filePath) {
  const content = fs.readFileSync(filePath, "utf8");
  const regex = /```mermaid\n([\s\S]*?)```/g;
  const blocks = [];
  let match;
  while ((match = regex.exec(content)) !== null) {
    blocks.push(match[1].trim());
  }
  return blocks;
}

export function validateArchitectureDir(archDir, { label = archDir } = {}) {
  const files = listArchitectureMarkdown(archDir);
  const entries = files.flatMap((file) =>
    extractMermaidBlocks(file).map((source, index) => ({
      file: path.basename(file),
      index,
      source,
    })),
  );

  if (entries.length === 0) {
    return { ok: true, count: 0, failed: 0, label };
  }

  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "mermaid-validate-"));
  let failed = 0;

  for (const [i, entry] of entries.entries()) {
    const input = path.join(tmpDir, `diagram-${i}.mmd`);
    const output = path.join(tmpDir, `diagram-${i}.svg`);
    fs.writeFileSync(input, entry.source, "utf8");
    try {
      execSync(
        `npx --yes @mermaid-js/mermaid-cli@${MERMAID_CLI_VERSION} -i "${input}" -o "${output}"`,
        { stdio: "pipe" },
      );
    } catch {
      failed += 1;
      console.error(`✗ ${label} — ${entry.file} #${entry.index + 1}`);
    }
  }

  fs.rmSync(tmpDir, { recursive: true, force: true });
  return { ok: failed === 0, count: entries.length, failed, label };
}

export function exportArchitectureSvgs(archDir, outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  const tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "mermaid-export-"));
  let exported = 0;

  for (const file of listArchitectureMarkdown(archDir)) {
    const base = path.basename(file, ".md");
    const blocks = extractMermaidBlocks(file);
    blocks.forEach((source, index) => {
      const suffix = blocks.length > 1 ? `-${index + 1}` : "";
      const input = path.join(tmpDir, `${base}${suffix}.mmd`);
      const output = path.join(outDir, `${base}${suffix}.svg`);
      fs.writeFileSync(input, source, "utf8");
      execSync(
        `npx --yes @mermaid-js/mermaid-cli@${MERMAID_CLI_VERSION} -i "${input}" -o "${output}"`,
        { stdio: "inherit" },
      );
      exported += 1;
    });
  }

  fs.rmSync(tmpDir, { recursive: true, force: true });
  return exported;
}

export function architectureBodyFromDir(archDir) {
  const sources = fs
    .readdirSync(archDir)
    .filter((f) => f.endsWith(".md") && f !== "README.md")
    .sort();

  return sources
    .map((name) => {
      const raw = fs.readFileSync(path.join(archDir, name), "utf8");
      return raw.replace(/^# /gm, "## ").trim();
    })
    .join("\n\n");
}

export function buildOrbitWrite({ project, archDir, date = new Date().toISOString().slice(0, 10) }) {
  const body = architectureBodyFromDir(archDir);
  const frontmatter = `---
title: "${project.title}"
summary: "${project.summary}"
date: "${date}"
category: "${project.category}"
featured: false
autoGenerated: true
tags: ${JSON.stringify(project.tags)}
---

{/* AUTO-GENERATED from ${project.dir}/docs/architecture/ — edit source there, then npm run arch:sync-all */}

`;

  const intro = `Canonical architecture for **${project.dir}**. Diagrams render live via Mermaid on Orbit.

`;

  return `${frontmatter}${intro}${body}\n`;
}
