/**
 * AUTO-GENERATED by `npm run powerbi:sync` — do not edit by hand.
 * Source: Power BI repo screenshots + README Pages tables.
 * Config: power-bi-projects.json
 */

export interface PowerBiReportPage {
  id: string;
  label: string;
  caption: string;
  src: string;
}

export interface PowerBiReport {
  id: string;
  title: string;
  summary: string;
  repoUrl?: string;
  /** Optional interactive demo (e.g. Vercel board for Nordic Equity). */
  liveUrl?: string;
  pages: PowerBiReportPage[];
}

export const powerBiReports: PowerBiReport[] = [
  {
    id: "finance",
    title: "Nordic Equity",
    summary: "Near-live Nordic large-cap board — TradingView-style sector heatmap, ticker explorer, and an RSI mean-reversion signal desk with classic day-trading indicators.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    liveUrl: "https://heatmap-web-five.vercel.app",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Artistic cover · thesis · audience · page map · EW cumulative hero",
        src: "/portfolio/power-bi/finance/landing.png",
      },
      {
        id: "nordic-heatmap",
        label: "Nordic Heatmap",
        caption: "Sector/company treemap · KPIs · open live board",
        src: "/portfolio/power-bi/finance/nordic-heatmap.png",
      },
      {
        id: "ticker-explorer",
        label: "Ticker Explorer",
        caption: "Single-ticker price, SMA, MACD, RSI, volume",
        src: "/portfolio/power-bi/finance/ticker-explorer.png",
      },
      {
        id: "signal-desk",
        label: "Signal Desk",
        caption: "RSI long/short queue · hit rates · equal-weight backtest",
        src: "/portfolio/power-bi/finance/signal-desk.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "Delay, indicators, caveats (last visible)",
        src: "/portfolio/power-bi/finance/context.png",
      },
    ],
  },
  {
    id: "churn",
    title: "E-commerce Churn Retention",
    summary: "Nordic Boardroom retention report: churn rate and propensity at a glance, driver analysis (Key Influencers + decomposition), and an at-risk intervention queue.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Artistic cover · thesis · audience · page map (opens first)",
        src: "/portfolio/power-bi/churn/landing.png",
      },
      {
        id: "retention-pulse",
        label: "Retention Pulse",
        caption: "KPI strip · churn rate by tenure band",
        src: "/portfolio/power-bi/churn/retention-pulse.png",
      },
      {
        id: "churn-drivers",
        label: "Churn Drivers",
        caption: "Key Influencers · decomposition tree · payment × city-tier matrix",
        src: "/portfolio/power-bi/churn/churn-drivers.png",
      },
      {
        id: "at-risk-queue",
        label: "At-Risk Queue",
        caption: "Customers ranked by `ChurnProbability` · risk / city / satisfaction slicers",
        src: "/portfolio/power-bi/churn/at-risk-queue.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "Facts-only reference · drivers how-to · data/model caveats (last visible)",
        src: "/portfolio/power-bi/churn/context.png",
      },
    ],
  },
  {
    id: "sales",
    title: "Sales Executive",
    summary: "Nordic Boardroom executive report for sales health: status in seconds, then self-serve into product drivers and customer/market concentration.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Artistic cover · thesis · audience · page map (opens first)",
        src: "/portfolio/power-bi/sales/landing.png",
      },
      {
        id: "portfolio-pulse",
        label: "Portfolio Pulse",
        caption: "KPI strip (value + YoY up/down) · monthly revenue trend · category mix",
        src: "/portfolio/power-bi/sales/portfolio-pulse.png",
      },
      {
        id: "performance-drivers",
        label: "Performance Drivers",
        caption: "Filter rail · category / product line · top 15 products · margin & YoY callouts",
        src: "/portfolio/power-bi/sales/performance-drivers.png",
      },
      {
        id: "customer-market",
        label: "Customer & Market",
        caption: "Country revenue & YoY · top 15 customers · concentration KPIs",
        src: "/portfolio/power-bi/sales/customer-market.png",
      },
    ],
  },
  {
    id: "supply-chain",
    title: "Logistics Pulse",
    summary: "COO-style **on-time delivery + demand forecast** report: delivery pulse, seller risk, and a weekly demand outlook with prediction-interval bounds.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Poster · On-time % hero · page map · `harbor-mist`",
        src: "/portfolio/power-bi/supply-chain/landing.png",
      },
      {
        id: "delivery-pulse",
        label: "Delivery Pulse",
        caption: "On-time · lead time · late volume · monthly trend · category mix",
        src: "/portfolio/power-bi/supply-chain/delivery-pulse.png",
      },
      {
        id: "sellers-routes",
        label: "Sellers & Routes",
        caption: "Seller late-rate queue · corridor table · freight vs late scatter",
        src: "/portfolio/power-bi/supply-chain/sellers-routes.png",
      },
      {
        id: "demand-outlook",
        label: "Demand Outlook",
        caption: "Signature — actual / dashed forecast / dotted 80% PI bounds",
        src: "/portfolio/power-bi/supply-chain/demand-outlook.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "On-time definition · forecast caveats · sample disclaimer",
        src: "/portfolio/power-bi/supply-chain/context.png",
      },
    ],
  },
  {
    id: "bank",
    title: "Bank Value & Engagement",
    summary: "Nordic Boardroom retail-bank report: dual-flow KPIs, RFM/k-means segments, geocoded city footprint, and a dormancy / cross-sell relationship book with drillthrough.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Artistic cover · thesis · audience · page map (opens first)",
        src: "/portfolio/power-bi/bank/landing.png",
      },
      {
        id: "franchise-pulse",
        label: "Franchise Pulse",
        caption: "Credit / debit / net flow · waterfall bridge · monthly volume",
        src: "/portfolio/power-bi/bank/franchise-pulse.png",
      },
      {
        id: "segments-markets",
        label: "Segments & Markets",
        caption: "Value segment mix · F×M scatter · Icon Map (OpenTopoMap)",
        src: "/portfolio/power-bi/bank/segments-markets.png",
      },
      {
        id: "relationship-book",
        label: "Relationship Book",
        caption: "Dormant + single-product queue · engagement funnel · drillthrough",
        src: "/portfolio/power-bi/bank/relationship-book.png",
      },
    ],
  },
  {
    id: "healthcare-analytics",
    title: "Care Pulse",
    summary: "30-day readmission propensity, admission→disposition pathways, and a discharge risk queue for hospital quality storytelling.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Artistic cover · thesis · audience · page map (opens first)",
        src: "/portfolio/power-bi/healthcare-analytics/landing.png",
      },
      {
        id: "care-pulse",
        label: "Care Pulse",
        caption: "KPI strip · monthly volume · readmit by diagnosis",
        src: "/portfolio/power-bi/healthcare-analytics/care-pulse.png",
      },
      {
        id: "pathways-drivers",
        label: "Pathways & Drivers",
        caption: "Sankey admission→disposition · age × diagnosis heat · discharge-group bars",
        src: "/portfolio/power-bi/healthcare-analytics/pathways-drivers.png",
      },
      {
        id: "discharge-risk-queue",
        label: "Discharge Risk Queue",
        caption: "Encounters ranked by `ReadmitProbability` · risk / age / discharge slicers",
        src: "/portfolio/power-bi/healthcare-analytics/discharge-risk-queue.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "Facts-only reference · Sankey how-to · data/model caveats (last visible)",
        src: "/portfolio/power-bi/healthcare-analytics/context.png",
      },
    ],
  },
  {
    id: "customer-experience",
    title: "Experience Pulse",
    summary: "CX / VoC **review-score** report with **detractor propensity** (logistic), Key Influencers, score erosion by delivery, and a probability-ranked recovery queue.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Poster · Avg Review Score hero · page map · `linen-mist`",
        src: "/portfolio/power-bi/customer-experience/landing.png",
      },
      {
        id: "experience-pulse",
        label: "Experience Pulse",
        caption: "Avg score · CSAT % · proxy NPS · avg detractor probability · trend",
        src: "/portfolio/power-bi/customer-experience/experience-pulse.png",
      },
      {
        id: "drivers",
        label: "Drivers",
        caption: "Tall Key Influencers · decomposition + theme matrix · score erosion",
        src: "/portfolio/power-bi/customer-experience/drivers.png",
      },
      {
        id: "recovery-queue",
        label: "Recovery Queue",
        caption: "Prioritization scatter · risk funnel · ranked by `DetractorProbability`",
        src: "/portfolio/power-bi/customer-experience/recovery-queue.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "Metric + model caveats (sample logistic, not production CX)",
        src: "/portfolio/power-bi/customer-experience/context.png",
      },
    ],
  },
  {
    id: "credit-risk",
    title: "Credit Risk Pulse",
    summary: "Nordic Boardroom **PD scorecard + cut-off strategy + monitoring + steering** report for consumer credit — domain flagship.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "Poster cover · thesis · OOT Gini hero · page map",
        src: "/portfolio/power-bi/credit-risk/landing.png",
      },
      {
        id: "portfolio-risk-pulse",
        label: "Portfolio Risk Pulse",
        caption: "Applications · default rate · Avg PD · EL rate · grade / risk band",
        src: "/portfolio/power-bi/credit-risk/portfolio-risk-pulse.png",
      },
      {
        id: "scorecard-validation",
        label: "Scorecard & Validation",
        caption: "Train/Test/OOT Gini · ROC · PD density · OOT calibration",
        src: "/portfolio/power-bi/credit-risk/scorecard-validation.png",
      },
      {
        id: "cutoff-strategy",
        label: "Cut-off Strategy",
        caption: "Acceptance frontier (new vs EXT_MEAN) · budget · operating / Youden policy",
        src: "/portfolio/power-bi/credit-risk/cutoff-strategy.png",
      },
      {
        id: "monitoring-steering",
        label: "Monitoring & Steering",
        caption: "New-business PD vs realized · PSI on IVs · steering queue",
        src: "/portfolio/power-bi/credit-risk/monitoring-steering.png",
      },
      {
        id: "context",
        label: "Context",
        caption: "Home Credit attribution · sample-model caveats · champion metrics",
        src: "/portfolio/power-bi/credit-risk/context.png",
      },
    ],
  },
  {
    id: "investing-desk",
    title: "Investment Portfolio",
    summary: "CIO-style **multi-sleeve investment portfolio** report: strategic allocation, excess return vs VWCE, holdings & rebalance, mandate compliance, Nordic regional tape.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "landing",
        label: "Landing",
        caption: "CIO poster · Excess CAGR vs Core hero · page map",
        src: "/portfolio/power-bi/investing-desk/landing.png",
      },
      {
        id: "asset-allocation",
        label: "Asset Allocation",
        caption: "Sleeve weights · ring-fence context (weights only)",
        src: "/portfolio/power-bi/investing-desk/asset-allocation.png",
      },
      {
        id: "performance",
        label: "Performance",
        caption: "Indexed equity · drawdown · Sharpe peers + gap vs VWCE",
        src: "/portfolio/power-bi/investing-desk/performance.png",
      },
      {
        id: "holdings-rebalance",
        label: "Holdings & Rebalance",
        caption: "Book weights · EXIT/ENTER/TRIM/DEFER",
        src: "/portfolio/power-bi/investing-desk/holdings-rebalance.png",
      },
      {
        id: "risk-mandate",
        label: "Risk & Mandate",
        caption: "Vol / MDD · book 95% VaR · book vs optimizer weights · IPS rules",
        src: "/portfolio/power-bi/investing-desk/risk-mandate.png",
      },
      {
        id: "regional-markets",
        label: "Regional Markets",
        caption: "Nordic overlap · [live board](https://heatmap-web-five.vercel.app) CTA",
        src: "/portfolio/power-bi/investing-desk/regional-markets.png",
      },
      {
        id: "notes",
        label: "Notes",
        caption: "Methodology · not advice · refresh path",
        src: "/portfolio/power-bi/investing-desk/notes.png",
      },
    ],
  },
];
