/**
 * AUTO-GENERATED by `npm run powerbi:sync` — do not edit by hand.
 * Source: Power BI repo screenshots + README Pages tables.
 * Config: power-bi-projects.json
 */

export interface PowerBiReportPage {
  id: string;
  label: string;
  caption: string;
  src: string;
}

export interface PowerBiReport {
  id: string;
  title: string;
  summary: string;
  repoUrl?: string;
  pages: PowerBiReportPage[];
}

export const powerBiReports: PowerBiReport[] = [
  {
    id: "churn",
    title: "E-commerce Churn Retention",
    summary: "Nordic Boardroom retention report: churn rate and propensity at a glance, driver analysis (Key Influencers + decomposition), and an at-risk intervention queue.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "retention-pulse",
        label: "Retention Pulse",
        caption: "KPI strip · churn rate by tenure band",
        src: "/portfolio/power-bi/churn/retention-pulse.png",
      },
      {
        id: "churn-drivers",
        label: "Churn Drivers",
        caption: "Key Influencers · decomposition tree · payment × city-tier matrix",
        src: "/portfolio/power-bi/churn/churn-drivers.png",
      },
      {
        id: "at-risk-queue",
        label: "At-Risk Queue",
        caption: "Customers ranked by `ChurnProbability` · risk / city / satisfaction slicers",
        src: "/portfolio/power-bi/churn/at-risk-queue.png",
      },
    ],
  },
  {
    id: "sales",
    title: "Sales Executive",
    summary: "Nordic Boardroom executive report for sales health: status in seconds, then self-serve into product drivers and customer/market concentration.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "portfolio-pulse",
        label: "Portfolio Pulse",
        caption: "KPI strip (value + YoY up/down) · monthly revenue trend · category mix",
        src: "/portfolio/power-bi/sales/portfolio-pulse.png",
      },
      {
        id: "performance-drivers",
        label: "Performance Drivers",
        caption: "Filter rail · category / product line · top 15 products · margin & YoY callouts",
        src: "/portfolio/power-bi/sales/performance-drivers.png",
      },
      {
        id: "customer-market",
        label: "Customer & Market",
        caption: "Country revenue & YoY · top 15 customers · concentration KPIs",
        src: "/portfolio/power-bi/sales/customer-market.png",
      },
    ],
  },
  {
    id: "bank",
    title: "Bank Value & Engagement",
    summary: "Nordic Boardroom retail-bank report: dual-flow KPIs, RFM/k-means segments, geocoded city footprint, and a dormancy / cross-sell relationship book with drillthrough.",
    repoUrl: "https://github.com/AlexTouvras/powerbi-portfolio",
    pages: [
      {
        id: "franchise-pulse",
        label: "Franchise Pulse",
        caption: "Credit / debit / net flow · waterfall bridge · monthly volume",
        src: "/portfolio/power-bi/bank/franchise-pulse.png",
      },
      {
        id: "segments-markets",
        label: "Segments & Markets",
        caption: "Value segment mix · F×M scatter · Icon Map (OpenTopoMap)",
        src: "/portfolio/power-bi/bank/segments-markets.png",
      },
      {
        id: "relationship-book",
        label: "Relationship Book",
        caption: "Dormant + single-product queue · engagement funnel · drillthrough",
        src: "/portfolio/power-bi/bank/relationship-book.png",
      },
    ],
  },
];
